year3/developingInternetApplications/rubyOnRailsIntro/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :posts
  resources :users

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

year3/developingInternetApplications/rubyOnRailsIntro/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

year3/developingInternetApplications/rubyOnRailsIntro/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  def get_body_short
    body[0..80] + '...'
  end
end

year3/developingInternetApplications/rubyOnRailsIntro/app/models/user.rb
class User < ApplicationRecord

  has_many :posts, dependent: :destroy

  def full_name
    "#{firstname} #{lastname}"
  end

end

year3/developingInternetApplications/rubyOnRailsIntro/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

year3/developingInternetApplications/rubyOnRailsIntro/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.paginate(:page => params[:page], :per_page => params[:per].nil? ? 30 : params[:per])
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :user_id)
    end
end

year3/developingInternetApplications/rubyOnRailsIntro/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.paginate(:page => params[:page], :per_page => (params[:per].nil? ? 30 : params[:per]))
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:firstname, :lastname, :email)
    end
end

year3/developingInternetApplications/rubyOnRailsIntro/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

year3/developingInternetApplications/rubyOnRailsIntro/app/helpers/application_helper.rb
module ApplicationHelper
end

year3/developingInternetApplications/rubyOnRailsIntro/app/helpers/posts_helper.rb
module PostsHelper
end

year3/developingInternetApplications/rubyOnRailsIntro/app/helpers/users_helper.rb
module UsersHelper
end

year3/developingInternetApplications/rubyOnRailsIntro/app/helpers/welcome_helper.rb
module WelcomeHelper
end

year3/developingInternetApplications/rubyOnRailsIntro/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>SE31520</title>
    <%= csrf_meta_tags %>

    <%#= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>

  <body>

    <div class="container">
      <div class="navigation">
        <%= render_navigation renderer: BootstrapNavigationRenderer %>
      </div>

      <div class="content">
        <%= yield %>
      </div>
    </div>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

year3/developingInternetApplications/rubyOnRailsIntro/app/views/posts/_form.html.erb
<%
# Placed up here to avoid possible duplication in do loop
user_collection = collection_select(:post, :user_id, User.all, :id, :email, {}, { :class => 'form-control' } )
%>

<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, { class: 'form-control' } %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, { class: 'form-control' }  %>
  </div>

  <div class="form-group">
    <%= f.label :user_id %>

    <%= user_collection %>
  </div>

  <div class="form-group">
    <%= f.submit({ class: 'btn btn-primary' }) %>
  </div>
<% end %>

year3/developingInternetApplications/rubyOnRailsIntro/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

year3/developingInternetApplications/rubyOnRailsIntro/app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.get_body_short %></td>
        <td><%= "#{post.user.full_name} (id #{post.user.id})"%></td>
        <td><%= link_to 'Show', post, { class: 'btn btn-default', role: 'button' } %></td>
        <td><%= link_to 'Edit', edit_post_path(post), { class: 'btn btn-default', role: 'button' } %></td>
        <td><%= link_to 'Destroy', post, { class: 'btn btn-danger', role: 'button', method: :delete, data: { confirm: 'Are you sure?' } } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'New Post', new_post_path, { class: 'btn btn-primary' } %>
<br>
<%= will_paginate @posts %>
<br>

year3/developingInternetApplications/rubyOnRailsIntro/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

year3/developingInternetApplications/rubyOnRailsIntro/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>User:</strong>
  <%= link_to "#{@post.user.email}", "/users/#{@post.user.id}"%>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

year3/developingInternetApplications/rubyOnRailsIntro/app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :firstname %>
    <%= f.text_field :firstname, { class: 'form-control' } %>
  </div>

  <div class="form-group">
    <%= f.label :lastname %>
    <%= f.text_field :lastname, { class: 'form-control' } %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, { class: 'form-control' } %>
  </div>

  <div class="form-group">
    <%= f.submit({ class: 'btn btn-primary' })%>
  </div>
<% end %>

year3/developingInternetApplications/rubyOnRailsIntro/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

year3/developingInternetApplications/rubyOnRailsIntro/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.firstname %></td>
        <td><%= user.lastname %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user, { class: 'btn btn-default', role: 'button' } %></td>
        <td><%= link_to 'Edit', edit_user_path(user), { class: 'btn btn-default', role: 'button' } %></td>
        <td><%= link_to 'Destroy', user, { class: 'btn btn-danger', role: 'button', method: :delete, data: { confirm: 'Are you sure?' }} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New User', new_user_path, { class: 'btn btn-primary' } %>
<br>
<%= will_paginate @users %>
<br>

year3/developingInternetApplications/rubyOnRailsIntro/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

year3/developingInternetApplications/rubyOnRailsIntro/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @user.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.lastname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

year3/developingInternetApplications/rubyOnRailsIntro/app/views/welcome/index.html.erb
<h1>SE31520 Weblog</h1>
<hr />

<h3>
  Do you see any Teletubbies in here? Do you see a slender plastic tag clipped to my shirt with my name printed on it?
  Do you see a little Asian child with a blank expression on his face sitting outside on a mechanical helicopter that
  shakes when you put quarters in it? No? Well, that's what you see at a toy store. And you must think you're in a toy
  store, because you're here shopping for an infant named Jeb.
</h3>

<p>
  I am some static text
</p>